# Dockerfile for recording with asciinema

FROM python:3.9

WORKDIR /root

ADD config.json .
ADD languages.json .
ADD codewars-archiver.py .
ADD requirements.txt .
ADD docker/.config .config

RUN git config --global user.email "Docker@Docker.com"
RUN git config --global user.name "Docker"

RUN pip install --requirement requirements.txt asciinema

CMD ["asciinema", "rec", "app/recording.cast"]
